project_name: bm

before:
  hooks:
    - go test ./...

builds:
  - id: bm
    main: .
    binary: bm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: archive
    builds:
      - bm
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - assets/** 
      - "!tools/**"
      - "!internal_test/**"

nfpms:
  - id: bm
    package_name: bm
    builds:
      - bm
    homepage: https://github.com/Shu-AFK/bm
    description: "Bookmark Manager CLI"
    maintainer: "Floyd Göttsch <floyd.goettsch1@gmail.com>"
    license: MIT
    bindir: /usr/bin
    formats:
      - deb
      - rpm
      - archlinux

release:
  github:
    owner: Shu-AFK
    name: bm
  draft: false
  prerelease: auto

changelog:
  use: git

snapshot:
  name_template: "{{ .Tag }}-next"
